//! The order commands are listed in, which is the order the editor shows.

use super::*;

impl Command {
    pub const ALL: &'static [Command] = &[
        Command::New,
        Command::Open,
        Command::CloseTab,
        Command::NextTab,
        Command::PreviousTab,
        Command::Save,
        Command::SaveAs,
        Command::Export,
        Command::Quit,
        Command::Undo,
        Command::Redo,
        Command::Copy,
        Command::Cut,
        Command::Paste,
        Command::Duplicate,
        Command::Delete,
        Command::Group,
        Command::Pattern,
        Command::ConvertToMesh,
        Command::SplitIntoPieces,
        Command::Rejoin,
        Command::Rename,
        Command::ToggleVisibility,
        Command::MoveUp,
        Command::MoveDown,
        Command::FrameSelection,
        Command::FrameAll,
        Command::ViewTop,
        Command::ViewBottom,
        Command::ViewFront,
        Command::ViewBack,
        Command::ViewLeft,
        Command::ViewRight,
        Command::ViewIsometric,
        Command::ToggleGrid,
        Command::ToggleAxisX,
        Command::ToggleAxisY,
        Command::ToggleAxisZ,
        Command::ToggleSection,
        Command::DisplayShaded,
        Command::DisplayShadedEdges,
        Command::DisplayWireframe,
        Command::ToggleBoundingBox,
        Command::ToggleDocks,
        Command::ResetLayout,
        Command::ModeMove,
        Command::ModeRotate,
        Command::ModeResize,
        Command::ModeScale,
        Command::ToggleHandleFrame,
        Command::MeasureTool,
        Command::SnapToGeometry,
        Command::NudgeLeft,
        Command::NudgeRight,
        Command::NudgeUp,
        Command::NudgeDown,
        Command::NudgeAway,
        Command::NudgeToward,
    ];
}
