//! Every parameter each kind of pattern takes, and what a fresh one holds.

use super::*;
use crate::primitive::{ParamKind, ParamSpec, ParamValue, Params};

/// The parameter table: the fixed kinds' numbers, then every stage's, then the scatter's.
///
/// Stages are generated by the macro, since hand-writing eleven near-identical rows per stage
/// invited digit typos; only their defaults differ. Variations are not rows (issue 79): their
/// parameters are described on demand ([`vary_spec`]).
macro_rules! pattern_params {
    (
        [$($head:expr),* $(,)?],
        stages [$((
            $n:literal, $mode:expr, $count:expr, [$sx:expr, $sy:expr, $sz:expr], $turn:expr, $radius:expr
        )),* $(,)?],
        [$($tail:expr),* $(,)?]
    ) => {
        &[
            $($head,)*
            $(
                does(concat!("stage", $n, "_mode"), $mode),
                axis(concat!("stage", $n, "_axis"), ("kind", CUSTOM)),
                count(concat!("stage", $n, "_count"), concat!($n, " Copies"), $count, ("kind", CUSTOM)),
                length(concat!("stage", $n, "_step_x"), concat!($n, " Step X"), $sx, ("kind", CUSTOM)),
                length(concat!("stage", $n, "_step_y"), concat!($n, " Step Y"), $sy, ("kind", CUSTOM)),
                length(concat!("stage", $n, "_step_z"), concat!($n, " Step Z"), $sz, ("kind", CUSTOM)),
                angle(concat!("stage", $n, "_turn"), concat!($n, " Turn per copy"), $turn, ("kind", CUSTOM)),
                length(concat!("stage", $n, "_radius"), concat!($n, " Radius"), $radius, ("kind", CUSTOM)),
                length(concat!("stage", $n, "_growth"), concat!($n, " Radius per copy"), 0.0, ("kind", CUSTOM)),
                length(concat!("stage", $n, "_rise"), concat!($n, " Rise per copy"), 0.0, ("kind", CUSTOM)),
                // None by default, so rules from before variations lay out unchanged (issue 79).
                tally(concat!("stage", $n, "_variations"), concat!($n, " Variations"), MAX_VARIATIONS),
            )*
            $($tail,)*
        ]
    };
}

/// Every parameter a pattern can carry. The kind choice comes first and gates the rest.
pub const PARAMS: &[ParamSpec] = pattern_params!(
    [
        ParamSpec {
            key: "kind",
            label: "Kind",
            kind: ParamKind::Choice { options: KINDS },
            default: ParamValue::Choice(LINEAR),
            lock_group: 0,
            shown_when: None,
        },
        // Linear: a run of copies along a fixed step.
        count("count", "Copies", 3, ("kind", LINEAR)),
        length("step_x", "Step X", 20.0, ("kind", LINEAR)),
        length("step_y", "Step Y", 0.0, ("kind", LINEAR)),
        length("step_z", "Step Z", 0.0, ("kind", LINEAR)),
        // Grid: one count and one step per axis.
        count("grid_x", "Columns (X)", 3, ("kind", GRID)),
        count("grid_y", "Rows (Y)", 2, ("kind", GRID)),
        count("grid_z", "Layers (Z)", 1, ("kind", GRID)),
        length("grid_step_x", "Step X", 20.0, ("kind", GRID)),
        length("grid_step_y", "Step Y", 20.0, ("kind", GRID)),
        length("grid_step_z", "Step Z", 20.0, ("kind", GRID)),
        // Circular: copies evenly round a turn.
        count("circ_count", "Copies", 6, ("kind", CIRCULAR)),
        angle("circ_span", "Span", 360.0, ("kind", CIRCULAR)),
        length("circ_radius", "Radius", 0.0, ("kind", CIRCULAR)),
        axis("circ_axis", ("kind", CIRCULAR)),
        // Mirror: the original and its reflection across a plane.
        axis("mirror_axis", ("kind", MIRROR)),
        // Helix: turn and rise together.
        count("helix_count", "Copies", 8, ("kind", HELIX)),
        angle("helix_angle", "Angle per copy", 45.0, ("kind", HELIX)),
        length("helix_rise", "Rise per copy", 5.0, ("kind", HELIX)),
        length("helix_radius", "Radius", 20.0, ("kind", HELIX)),
        axis("helix_axis", ("kind", HELIX)),
        // Spiral: turn while the radius grows.
        count("spiral_count", "Copies", 12, ("kind", SPIRAL)),
        angle("spiral_angle", "Angle per copy", 30.0, ("kind", SPIRAL)),
        length("spiral_radius", "Start radius", 10.0, ("kind", SPIRAL)),
        length("spiral_growth", "Radius per copy", 5.0, ("kind", SPIRAL)),
        length("spiral_rise", "Rise per copy", 0.0, ("kind", SPIRAL)),
        axis("spiral_axis", ("kind", SPIRAL)),
        // Custom: a stack of stages, each repeating what the previous made (issue 67). Each stage picks
        // a mode first, then only the numbers it needs (issue 79). Labels carry the stage number because
        // value fields are remembered by label.
        count("stages", "Stages", 1, ("kind", CUSTOM)),
    ],
    stages [
        (1, 0, 3, [20.0, 0.0, 0.0], 0.0, 0.0),
        (2, 0, 2, [0.0, 20.0, 0.0], 0.0, 0.0),
        (3, 0, 2, [0.0, 0.0, 20.0], 0.0, 0.0),
        // The fourth opens as a turn, the one thing three runs cannot do.
        (4, 1, 4, [0.0, 0.0, 0.0], 90.0, 40.0),
    ],
    [
        // Noise (issue 79): how far each copy may wander. Not gated on kind.
        jitter("noise_x", "Jitter X"),
        jitter("noise_y", "Jitter Y"),
        jitter("noise_z", "Jitter Z"),
        // Per-axis turn jitter (issue 79), wrapped into [0, 360) like the transform panel's rotation.
        turn_jitter("noise_turn_x", "Jitter turn X"),
        turn_jitter("noise_turn_y", "Jitter turn Y"),
        turn_jitter("noise_turn_z", "Jitter turn Z"),
        // Size jitter either way, capped below 100% so a copy never shrinks to nothing.
        ParamSpec {
            key: "noise_scale",
            label: "Size jitter (%)",
            kind: ParamKind::Count { min: 0, max: 90 },
            default: ParamValue::Count(0),
            lock_group: 0,
            shown_when: None,
        },
        // The seed makes the scatter reproducible; another seed is another scatter of the same size.
        ParamSpec {
            key: "noise_seed",
            label: "Seed",
            kind: ParamKind::Count { min: 1, max: 9999 },
            default: ParamValue::Count(1),
            lock_group: 0,
            shown_when: None,
        },
        // Keep the original in place. Off by default, since older scatters moved it too.
        ParamSpec {
            key: "noise_keep_first",
            label: "Leave the original in place",
            kind: ParamKind::Bool,
            default: ParamValue::Bool(false),
            lock_group: 0,
            shown_when: None,
        },
    ]
);

/// The most copies one pattern lays down in total. Per-axis clamps cannot stop a grid multiplying
/// to millions of transforms, so the total is capped too.
pub const MAX_INSTANCES: usize = 4096;

/// The most stages a custom kind has. A fixed number lets stage numbers be ordinary named
/// parameters, which gives editing, saving, clipboard and undo for free.
pub const MAX_STAGES: usize = 4;

/// A fresh pattern's parameters.
pub fn default_params() -> Params {
    PARAMS.iter().map(|p| (p.key.to_string(), p.default)).collect()
}
