//! The tool that puts a mesh back into objects and groups (issue 108).
//!
//! Separates the mesh into bodies, recognises rebuildable shapes, and replaces the mesh with a
//! group of editable objects. See [`simple3d_geom::reassemble`] for the recognition.
//!
//! Unlike the simplify tool, the result is drawn over the mesh and only enters the document on
//! Reassemble: it is a new subtree, and swapping it in on every change would rebuild the outliner
//! under the pointer. Recognised shapes are drawn as built and the rest as boxes, over the
//! document's [`PreviewViewport`](simple3d_core::scene::PreviewViewport) setting. A non-modal
//! [in-place popup](crate::popup), so the model can be orbited while tuning.

mod open;
mod preview;
pub(crate) use preview::*;
mod run;
mod window;
pub(crate) use window::*;
mod controls;
pub(crate) use controls::*;
mod summary;
pub(crate) use summary::*;

use crate::worker::ReassembleJob;
use simple3d_core::mesh_data::MeshData;
use simple3d_core::primitive::ParamKind;
use simple3d_core::scene::NodeId;
use simple3d_core::xform::Xform;
use simple3d_geom::reassemble::{Assembly, Reassemble};
use std::hash::{Hash, Hasher};
use std::sync::Arc;

/// What the tool is working on while its window is open.
pub struct ReassembleTool {
    pub target: NodeId,
    /// The mesh as the document holds it, re-read when it changes under the non-modal tool.
    pub mesh: Arc<MeshData>,
    pub plan: Reassemble,
    /// The last finished run's result, with what it was asked.
    pub found: Option<Found>,
    /// The run in flight; at most one, since only the newest answer matters.
    pub job: Option<ReassembleJob>,
    /// Whether what was found is drawn over the mesh.
    pub outlines: bool,
    /// The mesh frame's world placement, so results computed in the mesh frame draw on the model.
    pub placement: Xform,
    /// The evaluation `placement` came from, to detect staleness.
    pub generation: u64,
}

impl ReassembleTool {
    /// Hash what the preview depends on into the viewport's image key. The found points are not
    /// hashed; they follow from these numbers.
    pub(crate) fn hash_preview<H: Hasher>(&self, hasher: &mut H) {
        self.target.hash(hasher);
        self.generation.hash(hasher);
        self.outlines.hash(hasher);
        self.found.is_some().hash(hasher);
        self.plan.recognise.hash(hasher);
        self.plan.group_touching.hash(hasher);
        self.plan.max_objects.hash(hasher);
        self.plan.tolerance.to_bits().hash(hasher);
        self.placement.hash_bits(hasher);
    }
}

/// A finished run, and the numbers it answered.
pub struct Found {
    pub plan: Reassemble,
    pub assembly: Arc<Assembly>,
    /// The overlay in the mesh's frame, computed once when the run lands.
    pub outline: Vec<Vec<simple3d_geom::Vec3>>,
    /// Whether that is few enough lines to draw at all.
    pub drawn: bool,
}

/// The popup's key, which also remembers where it was dragged.
const KEY: &str = "reassemble-tool";

/// The window width: a label and its field, and no more, since it covers the model.
const WIDTH: f32 = 340.0;

/// A number field's width: enough for a length with its unit.
const FIELD_WIDTH: f32 = 90.0;

/// The tolerance's range; zero means only shapes generated by this application.
const TOLERANCE: ParamKind = ParamKind::Length { min: 0.0 };

/// The object cap's range; the maximum only stops absurd typed numbers.
const OBJECTS: ParamKind = ParamKind::Count { min: 1, max: 10_000 };

/// The most line loops the preview draws per frame; past this nothing is drawn and the window
/// says so, since a partial picture would mislead.
const PREVIEW_LOOPS: usize = 12_000;
